package com.oracle.scancodedatabind.pojo;

import java.util.List;

/**
 * Result generated by scancode tool.
 */
public class ScancodeResult {

    private List<FileEntry> files;

    public List<FileEntry> getFiles() {
        return files;
    }

    public void setFiles(List<FileEntry> files) {
        this.files = files;
    }
}
